{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.10.10","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kaggle":{"accelerator":"nvidiaTeslaT4","dataSources":[],"dockerImageVersionId":30497,"isInternetEnabled":true,"language":"python","sourceType":"notebook","isGpuEnabled":true}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"markdown","source":"# Connect Your VSCode to Kaggle","metadata":{}},{"cell_type":"markdown","source":"## Update and clone the repo","metadata":{}},{"cell_type":"code","source":"# Updates the package lists for upgrades and new package installations.\n# The `-qq` flag is used to minimize the output, and `--allow-releaseinfo-change`\n# allows the update process to continue even if the release information has changed.\n!sudo apt update -qq > /dev/null 2>&1","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-10T08:06:54.166116Z","iopub.execute_input":"2025-03-10T08:06:54.166842Z","iopub.status.idle":"2025-03-10T08:06:57.469813Z","shell.execute_reply.started":"2025-03-10T08:06:54.166808Z","shell.execute_reply":"2025-03-10T08:06:57.468641Z"}},"outputs":[],"execution_count":8},{"cell_type":"code","source":"# Clone this Github repo to run scripts\n%cd /kaggle/working\n!git clone https://github.com/0xpix/Kaggle_SSH_VSCode.git\n%cd Kaggle_SSH_VSCode","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-10T08:03:46.410890Z","iopub.execute_input":"2025-03-10T08:03:46.411630Z","iopub.status.idle":"2025-03-10T08:03:48.078991Z","shell.execute_reply.started":"2025-03-10T08:03:46.411597Z","shell.execute_reply":"2025-03-10T08:03:48.077931Z"}},"outputs":[{"name":"stdout","text":"/kaggle/working\nCloning into 'Kaggle_SSH_VSCode'...\nremote: Enumerating objects: 81, done.\u001b[K\nremote: Counting objects: 100% (81/81), done.\u001b[K\nremote: Compressing objects: 100% (68/68), done.\u001b[K\nremote: Total 81 (delta 18), reused 68 (delta 8), pack-reused 0 (from 0)\u001b[K\nReceiving objects: 100% (81/81), 1.15 MiB | 9.15 MiB/s, done.\nResolving deltas: 100% (18/18), done.\n/kaggle/working/Kaggle_SSH_VSCode\n","output_type":"stream"}],"execution_count":3},{"cell_type":"code","source":"!bash install_cuda.sh","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-09T15:31:18.496382Z","iopub.execute_input":"2025-03-09T15:31:18.496780Z","iopub.status.idle":"2025-03-09T15:31:19.495214Z","shell.execute_reply.started":"2025-03-09T15:31:18.496752Z","shell.execute_reply":"2025-03-09T15:31:19.494313Z"}},"outputs":[{"name":"stdout","text":"CUDA is already installed, skipping installation.\n","output_type":"stream"}],"execution_count":9},{"cell_type":"markdown","source":"## Install SSH Server\n\nBefore setting up the SSH, \n\nStep 1: start by going to your terminal and generate an SSH key -> \nWindows: `ssh-keygen -t rsa -b 4096 -C \"kaggle_remote_ssh\" -f .ssh/kaggle_rsa`\nWSL: `ssh-keygen -t rsa -b 4096 -C \"kaggle_remote_ssh\" -f ~/.ssh/kaggle_rsa`\n\nStep 2: Run `cat ~/.ssh/kaggle_rsa.pub` and copy the key\n\nStep 3: Run `echo 'REPLACE_IT_WITH_YOUR_COPIED_KEY_FROM_STEP_2' >> ~/.ssh/authorized_keys`\n\nStep 3: Create a Github repo and put the file named `authorized_keys` in it.\n\nStep 4: go to the file and click raw and copy the url","metadata":{}},{"cell_type":"code","source":"# Step 5: Copy the url and run -> https://raw.githubusercontent.com/0xpix/SSH_Key_public/refs/heads/main/authorized_keys\n!bash install_ssh_server.sh \"authorized_keys_URL_FROM_STEP_4\"","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-10T08:07:02.613359Z","iopub.execute_input":"2025-03-10T08:07:02.614067Z","iopub.status.idle":"2025-03-10T08:07:07.844360Z","shell.execute_reply.started":"2025-03-10T08:07:02.614031Z","shell.execute_reply":"2025-03-10T08:07:07.843269Z"},"collapsed":true,"jupyter":{"outputs_hidden":true}},"outputs":[{"name":"stdout","text":"Setting up SSH keys...\nInstalling OpenSSH Server...\n223 packages can be upgraded. Run 'apt list --upgradable' to see them.\n\u001b[1;33mW: \u001b[0mhttp://packages.cloud.google.com/apt/dists/gcsfuse-focal/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.\u001b[0m\n\u001b[1;33mW: \u001b[0mhttps://packages.cloud.google.com/apt/dists/google-fast-socket/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.\u001b[0m\nReading package lists... Done\nBuilding dependency tree... Done\nReading state information... Done\nopenssh-server is already the newest version (1:8.9p1-3ubuntu0.11).\n0 upgraded, 0 newly installed, 0 to remove and 223 not upgraded.\nConfiguring SSH Server...\nRestarting SSH service...\n * Restarting OpenBSD Secure Shell server sshd\n   ...done.\nSSH server setup complete.\n","output_type":"stream"}],"execution_count":9},{"cell_type":"markdown","source":"## Setting-up zrok\n\nStep 1: [Create a zrok account](https://zrok.io/) -> Get Started -> Get an account \n\nStep 2:  -> go to [zrok api](https://api.zrok.io/) and copy your token","metadata":{}},{"cell_type":"code","source":"# Step 3: Install zrok\n!bash install_zrok.sh\n!zrok version","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-10T08:04:43.855928Z","iopub.execute_input":"2025-03-10T08:04:43.856856Z","iopub.status.idle":"2025-03-10T08:04:53.393819Z","shell.execute_reply.started":"2025-03-10T08:04:43.856817Z","shell.execute_reply":"2025-03-10T08:04:53.392726Z"},"collapsed":true,"jupyter":{"outputs_hidden":true}},"outputs":[{"name":"stdout","text":"Installing Zrok...\ncurl: /opt/conda/lib/libcurl.so.4: no version information available (required by curl)\nHit:1 http://packages.cloud.google.com/apt gcsfuse-focal InRelease\nHit:2 https://packages.cloud.google.com/apt cloud-sdk InRelease                \nHit:3 http://archive.ubuntu.com/ubuntu jammy InRelease                         \nHit:4 https://packages.cloud.google.com/apt google-fast-socket InRelease       \nHit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease                 \nHit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease               \nHit:7 http://security.ubuntu.com/ubuntu jammy-security InRelease               \nHit:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease\nGet:9 https://packages.openziti.org/zitipax-openziti-deb-stable debian InRelease [5125 B]\nGet:10 https://packages.openziti.org/zitipax-openziti-deb-stable debian/main amd64 Packages [11.1 kB]\nFetched 16.2 kB in 1s (15.8 kB/s)   \nReading package lists... Done\nW: http://packages.cloud.google.com/apt/dists/gcsfuse-focal/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.\nW: https://packages.cloud.google.com/apt/dists/google-fast-socket/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.\nReading package lists... Done\nBuilding dependency tree... Done\nReading state information... Done\nThe following NEW packages will be installed:\n  zrok\n0 upgraded, 1 newly installed, 0 to remove and 223 not upgraded.\nNeed to get 33.5 MB of archives.\nAfter this operation, 101 MB of additional disk space will be used.\nGet:1 https://packages.openziti.org/zitipax-openziti-deb-stable debian/main amd64 zrok amd64 0.4.49-1 [33.5 MB]\nFetched 33.5 MB in 1s (30.9 MB/s)\nSelecting previously unselected package zrok.\n(Reading database ... 118265 files and directories currently installed.)\nPreparing to unpack .../zrok_0.4.49-1_amd64.deb ...\nUnpacking zrok (0.4.49-1) ...\nSetting up zrok (0.4.49-1) ...\nPackage: zrok\nVersion: 0.4.49-1\nSection: default\nPriority: optional\nArchitecture: amd64\nLicense: Apache 2.0\nMaintainer: support@zrok.io\nInstalled-Size: 98192\nHomepage: https://zrok.io/\nDescription: zrok is a next-generation sharing platform, designed to make sharing network and file resources simple and\n secure.\nDescription-md5: 50f4575637eeab3e077e71f45fb403de\nFilename: pool/zrok/amd64/zrok_0.4.49-1_amd64.deb\nSHA1: 11ba74f7d168098b7444e23b736f95a617cc4f6a\nSHA256: adc4718dc6dad9558952d9f13e364f5cee1dda5c2c5657fffc15b19b14a4ac10\nSize: 33451898\n\nZrok installation completed!\n","output_type":"stream"}],"execution_count":5},{"cell_type":"code","source":"# Step 4: enable your zrok env\n!bash add_zrok_token.sh \"REPLACE_WITH_TOKEN_FROM_STEP_2\"","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-09T15:31:13.334665Z","iopub.execute_input":"2025-03-09T15:31:13.334973Z","iopub.status.idle":"2025-03-09T15:31:18.494854Z","shell.execute_reply.started":"2025-03-09T15:31:13.334947Z","shell.execute_reply":"2025-03-09T15:31:18.493775Z"},"_kg_hide-input":true},"outputs":[{"name":"stdout","text":"\u001b]10;?\u001b\\\u001b[6n[   3.052]    INFO main.(*enableCommand).run: the zrok environment was successfully enabled...\nZrok enabled successfully!\n","output_type":"stream"}],"execution_count":8},{"cell_type":"code","source":"# Step 5: Access Kaggle notebook remotely\n# Step 6: Copy the private key (It's under \"access your share with:\"\")\n# Step 7: Let's go to your terminal\n!bash run_ssh_server.sh","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-03-09T15:31:19.496790Z","iopub.execute_input":"2025-03-09T15:31:19.497711Z","execution_failed":"2025-03-09T16:06:35.392Z"},"collapsed":true,"jupyter":{"outputs_hidden":true}},"outputs":[{"name":"stdout","text":"[   2.234]    INFO sdk-golang/ziti.(*listenerManager).createSessionWithBackoff: {session token=[8549ebed-3cd3-44da-81e4-6e9cee7b1941]} new service session\n\u001b]10;?\u001b\\\u001b[6n\u001b]11;?\u001b\\\u001b[6n\u001b[?25l\u001b[?1049h\u001b[2J\u001b[1;1H\u001b[1;1H\u001b[?25l\u001b[94m│\u001b[0m   access your share with: \u001b[96mzrok access private    \u001b[94m│\u001b[0m\u001b[94m│\u001b[0m  [\u001b[91mPRIVATE\u001b[0m] [\u001b[96mTCPTUNNEL\u001b[0m]   \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                   fqo3t0n4tgx1\u001b[0m                   \u001b[94m│\u001b[0m\u001b[94m╰──────────────────────────╯\u001b[0m\n\u001b[94m╰──────────────────────────────────────────────────╯\u001b[0m                            \n\u001b[94m╭──────────────────────────────────────────────────────────────────────────────╮\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                                                                              \u001b[94m│\u001b[0m\n\u001b[94m╰──────────────────────────────────────────────────────────────────────────────╯\u001b[0m\u001b[24;0H\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[80D\u001b[2K\u001b[94m│\u001b[0m   access your share with: \u001b[96mzrok access private    \u001b[94m│\u001b[0m\u001b[94m│\u001b[0m  [\u001b[91mPRIVATE\u001b[0m] [\u001b[96mTCPTUNNEL\u001b[0m]   \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m                   fqo3t0n4tgx1\u001b[0m                   \u001b[94m│\u001b[0m\u001b[94m╰──────────────────────────╯\u001b[0m\n\u001b[94m╰──────────────────────────────────────────────────╯\u001b[0m                            \n\u001b[94m╭──────────────────────────────────────────────────────────────────────────────╮\u001b[0m\n\u001b[94m│\u001b[0m\u001b[90mSunday, 09-Mar-25 15:32:27 UTC\u001b[0m \u001b[93mziti-edge-router                               \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mconnId=2147483648, logical=ziti-                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msdk[router=tls:92c34dbe-a505-48d8-81f9                                        \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m-ae47bdcad1fe.production.netfoundry.io:443]\u001b[0m -                                 \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m> \u001b[91mACCEPT\u001b[0m 127.0.0.1:22                                                         \u001b[94m│\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m╰──────────────────────────────────────────────────────────────────────────────╯\u001b[0m\u001b[24;0H\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m╰──────────────────────────────────────────────────────────────────────────────╯\u001b[0m\n\u001b[94m╭──────────────────────────────────────────────────────────────────────────────╮\u001b[0m\n\u001b[94m│\u001b[0m[ 103.683]   ERROR zrok/endpoints.TXer: read error '127.0.0.1:22' -> 'ziti    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m-edge-                                                                        \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mrouter connId=2147483648, logical=ziti-sdk[router=tls:92c34dbe-a505-48d8-81f9-\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mae47bdcad1fe.production.netfoundry.io:443]': read tcp 127.0.0.1:39978-        \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m>127.0.0.1:22: use of closed network connection                               \u001b[94m│\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[94m╰──────────────────────────────────────────────────────────────────────────────╯\u001b[0m\u001b[24;0H\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0msdk[router=tls:92c34dbe-a505-48d8-81f9                                        \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m-ae47bdcad1fe.production.netfoundry.io:443]\u001b[0m -                                 \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m> \u001b[91mACCEPT\u001b[0m 127.0.0.1:22                                                         \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m\u001b[90mSunday, 09-Mar-25 15:33:04 UTC\u001b[0m \u001b[93mziti-edge-router                               \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mconnId=2147483649, logical=ziti-                                              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msdk[router=tls:92c34dbe-a505-48d8-81f9                                        \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m-ae47bdcad1fe.production.netfoundry.io:443]\u001b[0m -                                 \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m> \u001b[91mACCEPT\u001b[0m 127.0.0.1:22                                                         \u001b[94m│\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[24;0H\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0m\u001b[90mSunday, 09-Mar-25 15:33:35 UTC\u001b[0m \u001b[93mziti-edge-router                               \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mconnId=2147483650, logical=ziti-                                              \u001b[94m│\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[24;0H\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0m\u001b[90mSunday, 09-Mar-25 15:34:10 UTC\u001b[0m \u001b[93mziti-edge-router                               \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mconnId=2147483651, logical=ziti-                                              \u001b[94m│\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0mrouter connId=2147483648, logical=ziti-sdk[router=tls:92c34dbe-a505-48d8-81f9-\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mae47bdcad1fe.production.netfoundry.io:443]': read tcp 127.0.0.1:39978-        \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m>127.0.0.1:22: use of closed network connection                               \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[ 260.085]   ERROR zrok/endpoints.TXer: read error '127.0.0.1:22' -> 'ziti    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m-edge-                                                                        \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mrouter connId=2147483650, logical=ziti-sdk[router=tls:92c34dbe-a505-48d8-81f9-\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mae47bdcad1fe.production.netfoundry.io:443]': read tcp 127.0.0.1:33112-        \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m>127.0.0.1:22: use of closed network connection                               \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0mrouter connId=2147483650, logical=ziti-sdk[router=tls:92c34dbe-a505-48d8-81f9-\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mae47bdcad1fe.production.netfoundry.io:443]': read tcp 127.0.0.1:33112-        \u001b[94m│\u001b[0m\n\u001b[1B\u001b[94m│\u001b[0m[2087.740]   ERROR zrok/endpoints.TXer: read error '127.0.0.1:22' -> 'ziti    \u001b[94m│\u001b[0m\n\u001b[1B\u001b[94m│\u001b[0mrouter connId=2147483651, logical=ziti-sdk[router=tls:92c34dbe-a505-48d8-81f9-\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mae47bdcad1fe.production.netfoundry.io:443]': read tcp 127.0.0.1:51992-        \u001b[94m│\u001b[0m\n\u001b[1B\u001b[24;0H\u001b[1A\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0mrouter connId=2147483651, logical=ziti-sdk[router=tls:92c34dbe-a505-48d8-81f9-\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mae47bdcad1fe.production.netfoundry.io:443]': read tcp 127.0.0.1:51992-        \u001b[94m│\u001b[0m\n\u001b[1B\u001b[94m│\u001b[0m[2092.249]   ERROR zrok/endpoints.TXer: read error '127.0.0.1:22' -> 'ziti    \u001b[94m│\u001b[0m\n\u001b[1B\u001b[94m│\u001b[0mrouter connId=2147483649, logical=ziti-sdk[router=tls:92c34dbe-a505-48d8-81f9-\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mae47bdcad1fe.production.netfoundry.io:443]': read tcp 127.0.0.1:57498-        \u001b[94m│\u001b[0m\n\u001b[1B\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0mrouter connId=2147483649, logical=ziti-sdk[router=tls:92c34dbe-a505-48d8-81f9-\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mae47bdcad1fe.production.netfoundry.io:443]': read tcp 127.0.0.1:57498-        \u001b[94m│\u001b[0m\n\u001b[1B\u001b[94m│\u001b[0m[2107.162] WARNING sdk-golang/ziti.(*ContextImpl).createSession: {error=[error\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfor request EWPaKtnFt: NOT_FOUND: The resource requested was not found or is  \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mno longer available, caused by: error for request : UNHANDLED: service with id\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m99m6OUNyoBHKoIVYBJpvu not found] errorType=[*rest_util.APIFormattedError]}    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfailure creating Bind session to service fqo3t0n4tgx1                         \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0m>127.0.0.1:22: use of closed network connection                               \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2107.162] WARNING sdk-golang/ziti.(*ContextImpl).createSession: {error=[error\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfor request EWPaKtnFt: NOT_FOUND: The resource requested was not found or is  \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mno longer available, caused by: error for request : UNHANDLED: service with id\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m99m6OUNyoBHKoIVYBJpvu not found] errorType=[*rest_util.APIFormattedError]}    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfailure creating Bind session to service fqo3t0n4tgx1                         \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2107.182]    INFO sdk-golang/ziti.(*ContextImpl).Authenticate: previous      \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mapiSession refreshed                                                          \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0mfailure creating Bind session to service fqo3t0n4tgx1                         \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2107.182]    INFO sdk-golang/ziti.(*ContextImpl).Authenticate: previous      \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mapiSession refreshed                                                          \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2108.293] WARNING sdk-golang/ziti.(*ContextImpl).createSession: {error=[error\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfor request 0pNOKt9F2: UNAUTHORIZED: The request could not be completed. The  \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msession is not authorized or the credentials are invalid]                     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0merrorType=[*rest_util.APIFormattedError]} failure creating Bind session to    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mservice fqo3t0n4tgx1                                                          \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0msession is not authorized or the credentials are invalid]                     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0merrorType=[*rest_util.APIFormattedError]} failure creating Bind session to    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mservice fqo3t0n4tgx1                                                          \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2108.312]   ERROR sdk-golang/ziti.(*ContextImpl).refreshServices: {error=[[GE\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mT                                                                             \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m/current-api-session/service-updates][401] listServiceUpdatesUnauthorized     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m&{Error:0xc00134de00 Meta:0xc0003f7080}]} failed to check if service list     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mupdate is available                                                           \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0mservice fqo3t0n4tgx1                                                          \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2108.312]   ERROR sdk-golang/ziti.(*ContextImpl).refreshServices: {error=[[GE\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mT                                                                             \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m/current-api-session/service-updates][401] listServiceUpdatesUnauthorized     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m&{Error:0xc00134de00 Meta:0xc0003f7080}]} failed to check if service list     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mupdate is available                                                           \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2108.332]    INFO sdk-golang/ziti.(*ContextImpl).refreshServices: attempting \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mto re-authenticate                                                            \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0m&{Error:0xc00134de00 Meta:0xc0003f7080}]} failed to check if service list     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mupdate is available                                                           \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2108.332]    INFO sdk-golang/ziti.(*ContextImpl).refreshServices: attempting \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mto re-authenticate                                                            \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2108.351]    INFO sdk-golang/ziti.(*ContextImpl).createSession: {error=[error\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfor request tAuOK29Ft: UNAUTHORIZED: The request could not be completed. The  \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msession is not authorized or the credentials are invalid]} failed to refresh  \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mservices after create session returned 404 (likely for service)               \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0mfor request tAuOK29Ft: UNAUTHORIZED: The request could not be completed. The  \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msession is not authorized or the credentials are invalid]} failed to refresh  \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mservices after create session returned 404 (likely for service)               \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2109.480] WARNING sdk-golang/ziti.(*ContextImpl).createSession: {error=[error\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfor request kY6a7tnFt: UNAUTHORIZED: The request could not be completed. The  \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msession is not authorized or the credentials are invalid]                     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0merrorType=[*rest_util.APIFormattedError]} failure creating Bind session to    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mservice fqo3t0n4tgx1                                                          \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0msession is not authorized or the credentials are invalid]                     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0merrorType=[*rest_util.APIFormattedError]} failure creating Bind session to    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mservice fqo3t0n4tgx1                                                          \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2109.500]   ERROR sdk-golang/ziti.(*ContextImpl).refreshServices: {error=[[GE\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mT                                                                             \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m/current-api-session/service-updates][401] listServiceUpdatesUnauthorized     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m&{Error:0xc00117ecc0 Meta:0xc0003b3940}]} failed to check if service list     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mupdate is available                                                           \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0mservice fqo3t0n4tgx1                                                          \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2109.500]   ERROR sdk-golang/ziti.(*ContextImpl).refreshServices: {error=[[GE\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mT                                                                             \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m/current-api-session/service-updates][401] listServiceUpdatesUnauthorized     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m&{Error:0xc00117ecc0 Meta:0xc0003b3940}]} failed to check if service list     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mupdate is available                                                           \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2109.519]    INFO sdk-golang/ziti.(*ContextImpl).refreshServices: attempting \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mto re-authenticate                                                            \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0m&{Error:0xc00117ecc0 Meta:0xc0003b3940}]} failed to check if service list     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mupdate is available                                                           \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2109.519]    INFO sdk-golang/ziti.(*ContextImpl).refreshServices: attempting \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mto re-authenticate                                                            \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2109.539]    INFO sdk-golang/ziti.(*ContextImpl).createSession: {error=[error\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfor request fdfOK2net: UNAUTHORIZED: The request could not be completed. The  \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msession is not authorized or the credentials are invalid]} failed to refresh  \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mservices after create session returned 404 (likely for service)               \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0mfor request fdfOK2net: UNAUTHORIZED: The request could not be completed. The  \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msession is not authorized or the credentials are invalid]} failed to refresh  \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mservices after create session returned 404 (likely for service)               \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2112.265] WARNING sdk-golang/ziti.(*ContextImpl).createSession: {error=[error\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfor request IWBOKtnFt: UNAUTHORIZED: The request could not be completed. The  \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msession is not authorized or the credentials are invalid]                     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0merrorType=[*rest_util.APIFormattedError]} failure creating Bind session to    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mservice fqo3t0n4tgx1                                                          \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0mservice fqo3t0n4tgx1                                                          \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2112.284]    INFO sdk-                                                       \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mgolang/ziti.(*ContextImpl).RefreshApiSessionWithBackoff.func1: previous       \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mapiSession expired                                                            \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2112.284]    INFO sdk-golang/ziti.(*ContextImpl).Authenticate: {error=[error \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfor request rJBO7t9Ft: UNAUTHORIZED: The request could not be completed. The  \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msession is not authorized or the credentials are invalid]} previous apiSession\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfailed to refresh, attempting to authenticate                                 \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0m[2112.284]    INFO sdk-golang/ziti.(*ContextImpl).Authenticate: {error=[error \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfor request rJBO7t9Ft: UNAUTHORIZED: The request could not be completed. The  \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msession is not authorized or the credentials are invalid]} previous apiSession\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfailed to refresh, attempting to authenticate                                 \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2112.502]   ERROR sdk-golang/ziti.(*listenerManager).createSessionWithBackoff\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m:                                                                             \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m{error=[error for request pCBO72ne2: INVALID_AUTH: The authentication request \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfailed]} failed to create bind session for service 0xc0018bce80               \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0m{error=[error for request pCBO72ne2: INVALID_AUTH: The authentication request \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfailed]} failed to create bind session for service 0xc0018bce80               \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2112.642] WARNING sdk-golang/ziti.(*ContextImpl).createSession:              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m{errorType=[*rest_util.APIFormattedError] error=[error for request uiBa72nFtP:\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mUNAUTHORIZED: The request could not be completed. The session is not          \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mauthorized or the credentials are invalid, caused by: error for request :     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mUNHANDLED: unauthenticated for invalid credentials]} failure creating Bind    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msession to service fqo3t0n4tgx1                                               \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0mUNAUTHORIZED: The request could not be completed. The session is not          \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mauthorized or the credentials are invalid, caused by: error for request :     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mUNHANDLED: unauthenticated for invalid credentials]} failure creating Bind    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msession to service fqo3t0n4tgx1                                               \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2112.870]   ERROR sdk-golang/ziti.(*listenerManager).createSessionWithBackoff\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m:                                                                             \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m{error=[error for request ssBOKtne2: INVALID_AUTH: The authentication request \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfailed]} failed to create bind session for service 0xc0018bce80               \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0m{error=[error for request ssBOKtne2: INVALID_AUTH: The authentication request \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfailed]} failed to create bind session for service 0xc0018bce80               \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2113.009] WARNING sdk-golang/ziti.(*ContextImpl).createSession: {error=[error\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfor request 7FMO72nFtP: UNAUTHORIZED: The request could not be completed. The \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msession is not authorized or the credentials are invalid, caused by: error for\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mrequest : UNHANDLED: unauthenticated for invalid credentials]                 \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0merrorType=[*rest_util.APIFormattedError]} failure creating Bind session to    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mservice fqo3t0n4tgx1                                                          \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0msession is not authorized or the credentials are invalid, caused by: error for\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mrequest : UNHANDLED: unauthenticated for invalid credentials]                 \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0merrorType=[*rest_util.APIFormattedError]} failure creating Bind session to    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mservice fqo3t0n4tgx1                                                          \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2113.241]   ERROR sdk-golang/ziti.(*listenerManager).createSessionWithBackoff\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m:                                                                             \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m{error=[error for request 6HMaK29et: INVALID_AUTH: The authentication request \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfailed]} failed to create bind session for service 0xc0018bce80               \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0m{error=[error for request 6HMaK29et: INVALID_AUTH: The authentication request \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfailed]} failed to create bind session for service 0xc0018bce80               \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2113.480] WARNING sdk-golang/ziti.(*ContextImpl).createSession:              \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m{errorType=[*rest_util.APIFormattedError] error=[error for request kAMaKt9FtP:\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mUNAUTHORIZED: The request could not be completed. The session is not          \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mauthorized or the credentials are invalid, caused by: error for request :     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mUNHANDLED: unauthenticated for invalid credentials]} failure creating Bind    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msession to service fqo3t0n4tgx1                                               \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0mUNAUTHORIZED: The request could not be completed. The session is not          \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mauthorized or the credentials are invalid, caused by: error for request :     \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mUNHANDLED: unauthenticated for invalid credentials]} failure creating Bind    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msession to service fqo3t0n4tgx1                                               \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2113.693]   ERROR sdk-golang/ziti.(*listenerManager).createSessionWithBackoff\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m:                                                                             \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m{error=[error for request aOLOKtnF2: INVALID_AUTH: The authentication request \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfailed]} failed to create bind session for service 0xc0018bce80               \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0m{error=[error for request aOLOKtnF2: INVALID_AUTH: The authentication request \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfailed]} failed to create bind session for service 0xc0018bce80               \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2114.145] WARNING sdk-golang/ziti.(*ContextImpl).createSession: {error=[error\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfor request 54Fa7tnetP: UNAUTHORIZED: The request could not be completed. The \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0msession is not authorized or the credentials are invalid, caused by: error for\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mrequest : UNHANDLED: unauthenticated for invalid credentials]                 \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0merrorType=[*rest_util.APIFormattedError]} failure creating Bind session to    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mservice fqo3t0n4tgx1                                                          \u001b[94m│\u001b[0m\n\u001b[24;0H\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[2K\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[1A\u001b[80D\u001b[2K\u001b[94m╭──────────────────────────────────────────────────╮\u001b[0m\u001b[94m╭──────────────────────────╮\u001b[0m\n\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[1B\u001b[94m│\u001b[0msession is not authorized or the credentials are invalid, caused by: error for\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mrequest : UNHANDLED: unauthenticated for invalid credentials]                 \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0merrorType=[*rest_util.APIFormattedError]} failure creating Bind session to    \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mservice fqo3t0n4tgx1                                                          \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m[2114.382]   ERROR sdk-golang/ziti.(*listenerManager).createSessionWithBackoff\u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m:                                                                             \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0m{error=[error for request V9eaKt9F2: INVALID_AUTH: The authentication request \u001b[94m│\u001b[0m\n\u001b[94m│\u001b[0mfailed]} failed to create bind session for service 0xc0018bce80               \u001b[94m│\u001b[0m\n\u001b[24;0H","output_type":"stream"}],"execution_count":null}]}